# Generated by Django 6.0 on 2025-12-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('seller', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('offer', models.CharField(blank=True, max_length=50)),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
